In [25]:
import numpy as np


In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]

8

In [28]:
arr[1:4]
#slicing 

array([1, 2, 3])

In [29]:
arr[:5]

array([0, 1, 2, 3, 4])

In [30]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr = np.arange(0,11)

In [41]:
slice_of_arr = arr[0:6]

In [43]:
slice_of_arr[:] = 99 

In [45]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
 arr_copy = arr.copy()

In [51]:
arr_copy[:] = 100 

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [57]:
arr_2d = np.array(([2,3,4] , [4,5,6] , [5,6,7]))

In [59]:
arr_2d

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [61]:
arr_2d[0][0]

2

In [63]:
arr_2d[1][1]

5

In [65]:
arr_2d[2,1]

6

In [67]:
arr_2d[:2,1:]

array([[3, 4],
       [5, 6]])

In [73]:
bool_array = arr>5

In [75]:
bool_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [77]:
arr[bool_array]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
arr[arr>99]

array([], dtype=int32)

In [83]:
arr_2d = np.arange(50).reshape(5,10)

In [85]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
arr_2d[1:3 , 3:5]

array([[13, 14],
       [23, 24]])