In [117]:
##Numpy array

In [118]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [119]:
import numpy as np


In [120]:
arr = np.array(my_list)

In [121]:
arr

array([1, 2, 3])

In [122]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9] ]
my_matrix         

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [123]:
arr_matrix = np.array(my_matrix)
arr_matrix 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
 np.arange(0,11)
 np.arange(0,11 ,2)


array([ 0,  2,  4,  6,  8, 10])

In [125]:
 np.zeros(4)


array([0., 0., 0., 0.])

In [126]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
np.ones(3)

array([1., 1., 1.])

In [128]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [129]:
np.linspace(0,7,10)
# بتقسم مسافات مظبوطة ، يعني 10 اليمينت من صفر ل 7 متقسمين مثلا

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [130]:
np.eye(5)
#مصفوفة متطابقة

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [131]:
np.random.rand(5)

array([0.66161153, 0.58449435, 0.57516209, 0.79399059, 0.8626937 ])

In [132]:
np.random.rand(5,5)
#normal distribution 

array([[0.98346483, 0.1066264 , 0.40723771, 0.4123211 , 0.70696704],
       [0.98123016, 0.71147535, 0.42177214, 0.28450754, 0.74045756],
       [0.52084811, 0.58432807, 0.16418324, 0.78642564, 0.53348374],
       [0.09718978, 0.45856048, 0.3364739 , 0.59126102, 0.8829773 ],
       [0.64322494, 0.50503035, 0.41043131, 0.46643391, 0.55674645]])

In [133]:
np.random.randn(5,5)

array([[-1.27543833, -0.07949173, -0.11408438,  0.73425789,  0.3330275 ],
       [-0.96731282, -1.70727148,  0.13751741, -2.12662798, -1.80497599],
       [-1.12937633, -0.40966817,  0.62161294, -0.08844501,  0.83184282],
       [ 0.11127918, -0.82005573, -0.75159109,  1.98615552, -0.36873739],
       [ 1.64202307, -1.61514664,  1.90941619,  1.26581493, -0.16086742]])

In [134]:
np.random.randint(1,100,10)

array([34,  8,  1,  1, 42, 34, 18, 49, 37, 97])

In [135]:
arr = np.arange(25)

In [136]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [137]:
ranarr = np.random.randint(0,50 ,10 )

In [138]:
ranarr

array([13,  2, 24, 15,  5, 20, 16, 27, 22, 27])

In [139]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [140]:
ranarr.max()

27

In [141]:
ranarr.min()

2

In [142]:
ranarr.argmax()

7

In [143]:
ranarr.argmin()

1

In [144]:
arr.shape

(25,)

In [146]:
arr = arr.reshape(5,5)

In [148]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
arr.shape

(5, 5)

In [152]:
arr.dtype

dtype('int32')